const refs = {
  backdropModalImg: document.querySelector('.js-lightbox'),
  openModal: document.querySelector('[data-modal-open="openBtn"]'),
  backdropOverlay: document.querySelector('[data-modal="backdropOverlay"]'),
  modalOverlay: document.querySelector('[data-modal="aboutUsModal"]'),
  closeBtn: document.querySelector('[data-modal-close="closeBtn"]'),
  searchInputRef: document.querySelector('input[name="search"]'),
  searchInput: document.querySelector('.search__input-wrapper'),
  filmsMarkup: document.querySelector('.js-movies-container'),
  logo: document.querySelector('.logo'),
  homeBtn: document.querySelector('#home-button'),
  libraryBtn: document.querySelector('#library-button'),
  headerBg: document.querySelector('.header__background'),
  searchWrap: document.querySelector('.search__input-wrapper'),
  libraryBtnsContainer: document.querySelector('.button-container'),
  libraryBg: document.querySelector('.library__background'),
  heroBlock: document.querySelector('.hero'),
  paginationContainer: document.querySelector('.pagination__container'),
  filterInput: document.querySelectorAll('.filter-input'),
  watchedBtn: document.querySelector('.watched-button'),
  queueBtn: document.querySelector('.queue-button'),
  filter: document.querySelector('.filter-section'),
  searchInput: document.querySelector('.search__input'),
};

export default refs;
